name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn lint
      - run: yarn test
      - uses: browser-actions/setup-firefox@063eed68fefb6e72be98fb0c0d2d106784c79634
        with:
          firefox-version: latest-devedition
      - run: yarn test:e2e
