on: workflow_dispatch

name: Submit to Web Stores

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2
        with:
          node-version: '14'
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn package
      - name: Browser Plugin Publish
        uses: plasmo-corp/bpp@v1
        with:
          keys: ${{ secrets.SUBMIT_KEYS }}
